# Generated by Django 4.1.1 on 2022-09-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='abstract',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='heading',
            new_name='head',
        ),
    ]
