# Generated by Django 4.1.1 on 2022-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_abstract_article_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
