# Generated by Django 4.1.1 on 2022-09-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_date_alter_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
