# Generated by Django 4.1.1 on 2022-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_article_date_alter_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='interview',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
