# Generated by Django 4.1.1 on 2022-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_image_alter_interview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='interview',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
