# Generated by Django 4.1.1 on 2022-09-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_article_image_alter_interview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
